---    

- name: Create PostgreSQL user
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    state: present

- name: Create database
  postgresql_db:
    name: "{{ db_name }}"
    port: "{{ db_port }}"
    owner: "{{ db_user }}"
    state: present
    
- name: Grant ALL privileges to db_user
  postgresql_privs:
    type: database
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    privs: ALL
    grant_option: yes




