---
- name: Create backend directory
  file:
    path: /opt/todo-backend
    state: directory
    mode: 0755

- name: Copy backend files to server
  copy:
    src: files/Todo-back-main/  # Копируем всю папку
    dest: /opt/todo-backend/
    owner: qsyoma
    group: qsyoma
    mode: 0644

- name: Install Python dependencies
  pip:
    requirements: /opt/todo-backend/requirements.txt
    executable: pip3

#- name: Create environment file for backend
#  template:
#    src: templates/backend.env.j2
#    dest: /opt/todo-backend/.env 

#- name: Apply Django migrations
#  command: python3 manage.py migrate
#  args:
#    chdir: /opt/todo-backend/

#- name: Setup Gunicorn service
#  template:
#    src: templates/gunicorn.service.j2
#    dest: /etc/systemd/system/gunicorn.service
#  notify: restart gunicorn
