---
- name: Create frontend directory
  file:
    path: /opt/todo-frontend
    state: directory
    mode: 0755

- name: Copy frontend files to server
  copy:
    src: files/Todo-front-main/
    dest: /opt/todo-frontend/
    owner: qsyoma
    group: qsyoma
    mode: 0644

#- name: Install Node.js dependencies (если нужно)
#  command: npm install
#  args:
#    chdir: /opt/todo-frontend/
#  when: "'package.json' in lookup('file', '/opt/todo-#frontend/package.json')"

#- name: Build frontend (если нужно)
#  command: npm run build
#  args:
#    chdir: /opt/todo-frontend/
#  when: "'package.json' in lookup('file', '/opt/todo-frontend/package.json')"
