---
- name: Install Nginx
  apt:
    name: nginx
    state: latest
    
- name: Configure Nginx
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/todo
  notify: restart nginx
 
- name: Enable site
  file:
    src: /etc/nginx/sites-available/todo
    dest: /etc/nginx/sites-enabled/todo
    state: link
  notify: restart nginx

